### ISSUE TITLE
Possibility to integrate arch-go in tests

### ISSUE THREAD

**Issue by IceflowRE** [fdaines/arch-go#22]
Is there an option to integrate the test in go unit tests? And describe the rules via code and not using the yml configuration.
For example like [github.com/matthewmcnew/archtest](https://github.com/matthewmcnew/archtest) does.

**Comment by fdaines** [comment]
Hello! At this time there are no plans to expose a programmatic interface for Arch-Go.
Arch-go proposes a declarative approach over the programmatic one for a couple of reasons like:
* A declarative description of architecture rules is easier to understand than a set of function calls
* All rules live in one place (the YAML file), making it easier to share rules between projects and teams.
* Personally, I think architecture testing is beyond the scope of unit testing, so with a declarative approach I force myself to avoid mixing architecture tests and unit tests in the same step.

Think of Arch-Go Tool (and any architecture testing tool) the same way that we use a Linter Tool, both kind of tools verifies if our codebase complies with a set of predefined rules and uses a declarative approach. Is possible to expose a programmatic interface for linter tools? of course that it's possible, but maybe it's better to keep the declarative approach for the moment.

But anyway, if you need to have the Arch-Go functionalities to execute them programmatically, I invite you to collaborate on this project through Pull Requests, all help is always welcome.

Best Regards!

**Comment by IceflowRE** [comment]
Thank you for the response.

I do not fully agree with your 2nd and 3rd reason, as i think that every project is unique so, there have to be always changes to the rules and if they are nearly equal the changes will be negligible.
Also i am not a fan of running another executable, if i could just do `go test` and it covers both unit and architecture tests, but that is more a personal preference. Also a linter is more at the meta layer than the architecture which is part of the core of the project.

Thanks for the invitation, but i already found another solution. Leaving this open for other people.

**Comment by rationelis** [comment]
I would also like support for test integration 👍

**Comment by fdaines** [comment]
@rationelis , @IceflowRE the most recent version of Arch-Go (v1.5.0) exposes an API to include architecture tests programmatically.
