### ISSUE TITLE
arch-go breaks if it doesn't inform the maxParameters property

### ISSUE THREAD

**Issue by edmarSoaress** [fdaines/arch-go#28]
In a project using arch-go, we don't want to limit the number of parameters in a function, so we try to remove them. This causes arch-go to break

**how to test:**
 In the project root, run the arch-go command without adding maxParameters to the file

**Comment by fdaines** [comment]
Thanks for your report. There was an issue in functions rules.
Version v1.4.4 fixes this issue.
```
go install github.com/fdaines/arch-go@v1.4.4
```
