### ISSUE TITLE
I would like to enforce the absence of an external dependency

### ISSUE THREAD

**Issue by martinsson** [fdaines/arch-go#3]
**My problem**
I have a single repo with multiple micro-services. I'm ok that my services share some library code, but I do not want one micro-service go and import code from another service. This is an implicit rule in the team that has been broken and gotten undetected for a while now.

**Suggested solution**
I would like to have a rule that detects whenever module A refers to module B. As I understand it is possible to either

- package _a_ should not refer to package _b_ : dependenciesRules.shouldNotDependsOn
- module _A_ should only refer to external module _B_ : dependenciesRules.shouldOnlyDependsOnExternal

Which does not seem to be able to address my concern. Seems like it'd be easy enough to add that to the source code, unless there are some difficulties I haven't thought of.

**Alternative solutions**
I can't think of any so far

**Comment by fdaines** [comment]
Hi Johan, Thanks for sharing your use case, the truth is that I've never tested arch-go with a monorepo, so it's very probably that we will need to add a new feature or fix something.

Can you share an example of the source tree of your project? I just want to know at what level you separate the different microservices, and where are the `go.mod` files.

**Comment by martinsson** [comment]
So here's a minimal example https://github.com/martinsson/go-arch-example 

The problem is with service B that depends on A. The fact that there's  a "replace" directive in the mod file makes it even more convenient.

Two uses comes to mind.
1. Simply forbid an external dependency (can be used with a go-arch.yml at the root of service-b)
2. Disallow specific replace directives in go.mod files

**Comment by fdaines** [comment]
Johan, I created a pull request to add the new dependency rule, I think that this feature should solve your use case.
As an example, you can try the following `arch-go.yml`configuration in the `service-b` directory.
```
dependenciesRules:
  - package: "**.b-service.**"
    shouldNotDependsOnExternal:
      - "**.a-service.**"
```

**Comment by fdaines** [comment]
Johan, I accidentally closed this issue, can you check please if the update (v0.7.0) solves your use case?
Thanks.

**Comment by martinsson** [comment]
Indeed that seems great. It's what I tried originally. I'll test that

**Comment by martinsson** [comment]
It works. Great!

I guess the describe instruction should get an update as well
