### ISSUE TITLE
Arch-Go always returns exit code 0, even when compliance / coverage fails. Should return non-zero exit code

### ISSUE THREAD

**Issue by DGuhr** [fdaines/arch-go#35]
In order to use arch-go in CI environments, it'd be nice to make it configurable to return another exit code than zero in case the checks did not succeed.

Currently, when you run `arch-go` and then `echo $?` afterwards, it always returns zero, unless you are running from a directory where there's no `arch-go.yml`

Example of a workflow that should have failed [here](https://github.com/DGuhr/arch-go-action-example/actions/runs/9471245216/job/26094034578#step:2:192) - @dadrus and I are trying to build a github action out of this currently. I'll look more into it tomorrow, and maybe provide a PR.

**Comment by DGuhr** [comment]
@fdaines the fix is simply returning `result.Passed` instead of `return true` in `runRootCommand`- i just have Problems understanding the existing tests, so I struggle to come up with a new one. the first two tests are effectively just checking the if condition in runCommand when I see it correctly, so basically true = exitCode 0 and false = exitCode 1.  Test 3 checks the console output, pointing to your arch-go.yml in the test directory, but not the exitCode. Test 4 also does not go into the runRootCommand when I see it correctly. wdyt?

**Comment by fdaines** [comment]
Thanks @DGuhr , you're right the fiz is very simple, I'm going to check the comments about tests today and create a new release.

**Comment by DGuhr** [comment]
@fdaines np - i just provided a PR. feel free to check :)

**Comment by fdaines** [comment]
@DGuhr a new version was published (v1.5.4), can you check the behavior please?
```
go install github.com/fdaines/arch-go@v1.5.4
```

**Comment by DGuhr** [comment]
@fdaines it works now, thanks. see https://github.com/DGuhr/arch-go-action-example/actions/runs/9494018037/job/26163663800 which now failed, as it should.
